#!/usr/bin/env bash
#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

readonly BINDIR=$(dirname "$0")

badge() {
  local -r distro="$1"
  cat <<_EOF_

[![Kokoro readme ${distro} status][kokoro-readme-${distro}-shield]][kokoro-readme-${distro}-link]

[kokoro-readme-${distro}-shield]: https://storage.googleapis.com/cloud-cpp-kokoro-status/common/readme/${distro}.svg
[kokoro-readme-${distro}-link]: https://storage.googleapis.com/cloud-cpp-kokoro-status/common/readme/${distro}-link.html
_EOF_
}

readonly DOCKERFILES_DIR="${BINDIR}/../kokoro/readme"

cat <<_EOF_
# Google Google Cloud C++ Client Common Libraries

<!-- This file is automatically generated by ci/test-readme/$(basename "$0") -->

This repository contains common types and functions used by the
Google Cloud C++ Client Libraries.

_EOF_

"${BINDIR}/../generate-badges.sh"

cat <<'_EOF_'
## Table of Contents

- [Requirements](#requirements)
  - [Compiler](#compiler)
  - [Build Tools](#build-tools)
  - [Libraries](#libraries)
  - [Tests](#tests)
- [Install Dependencies](#install-dependencies)
  - [CentOS (8)](#centos-8)
  - [CentOS (7)](#centos-7)
  - [Debian (10 - Buster)](#debian-10---buster)
  - [Debian (9 - Stretch)](#debian-9---stretch)
  - [Fedora (30)](#fedora-30)
  - [openSuSE (Tumbleweed)](#opensuse-tumbleweed)
  - [openSuSE (Leap)](#opensuse-leap)
  - [Ubuntu (18.04 - Bionic Beaver)](#ubuntu-1804---bionic-beaver)
  - [Ubuntu (16.04 - Xenial Xerus)](#ubuntu-1604---xenial-xerus)
  - [macOS (using brew)](#macos-using-brew)
  - [Windows](#windows-using-vcpkg)
- [Build](#build)
  - [Linux](#linux)
  - [macOS](#macOS)
  - [Windows](#windows)
- [Install](#install)

## Requirements

#### Compiler

The Google Cloud C++ libraries are tested with the following compilers:

| Compiler    | Minimum Version |
| ----------- | --------------- |
| GCC         | 4.8 |
| Clang       | 3.8 |
| MSVC++      | 14.1 |
| Apple Clang | 8.1 |

#### Build Tools

The Google Cloud C++ Client Libraries can be built with
[CMake](https://cmake.org) or [Bazel](https://bazel.io).  The minimal versions
of these tools we test with are:

| Tool       | Minimum Version |
| ---------- | --------------- |
| CMake      | 3.5 |
| Bazel      | 0.24.0 |

#### Libraries

The libraries also depend on gRPC, libcurl, and the dependencies of those
libraries. The Google Cloud C++ Client libraries are tested with the following
versions of these dependencies:

| Library  | Minimum version |
| -------- | --------------- |
| protobuf | v3.11.3 |
| gRPC     | v1.26.x |
| libcurl  | 7.47.0  |

#### Tests

Integration tests at times use the
[Google Cloud SDK](https://cloud.google.com/sdk/). The integration tests run
against the latest version of the SDK on each commit and PR.

## Install Dependencies

_EOF_

echo "### CentOS (8)"
badge centos-8
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.centos-8"

echo "### CentOS (7)"
badge centos-7
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.centos-7"

echo "### Debian (10 - Buster)"
badge debian-buster
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.debian-buster"

echo "### Debian (9 - Stretch)"
badge debian-stretch
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.debian-stretch"

echo "### Fedora (30)"
badge fedora
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.fedora"

echo "### openSUSE (Tumbleweed)"
badge opensuse-tumbleweed
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.opensuse-tumbleweed"

echo "### openSUSE (Leap)"
badge opensuse-leap
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.opensuse-leap"

echo "### Ubuntu (18.04 - Bionic Beaver)"
badge ubuntu-bionic
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.ubuntu-bionic"

echo "### Ubuntu (16.04 - Xenial Xerus)"
badge ubuntu-xenial
"${BINDIR}/extract-readme.sh" "${DOCKERFILES_DIR}/Dockerfile.ubuntu-xenial"

cat <<'_EOF_'
#### macOS (using brew)

```bash
brew install curl cmake libressl c-ares
```

#### Windows (using vcpkg)

If you are already using [vcpkg][vcpkg-link], a package manager from Microsoft,
you can download and compile `google-cloud-cpp` in a single step:

```bash
.\vcpkg.exe install google-cloud-cpp:x64-windows-static
```

This command will also print out instructions on how to use the library from
your MSBuild or CMake-based projects. We try to keep the version of
`google-cloud-cpp` included with `vcpkg` up-to-date, our practice is to submit a
PR to update the version in `vcpkg` after each release of `google-cloud-cpp`.

See below for instructions to compile the code yourself.

[vcpkg-link]: https://github.com/Microsoft/vcpkg/

## Build

To build all available libraries and run the tests, run the following commands
after cloning this repo:

#### Linux

To automatically download the dependencies and compile the libraries and
examples you can use the CMake [super build][super-build-link]:

[super-build-link]: https://blog.kitware.com/cmake-superbuilds-git-submodules/

```bash
# Add -DBUILD_TESTING=OFF to disable tests
cmake -Hsuper -Bcmake-out

# Adjust the number of threads used by modifying parameter for `-j 4`
# following command will also invoke ctest at the end
cmake --build cmake-out -- -j 4
```

You will find compiled binaries in `cmake-out/` respective to their source
paths.

If you prefer to compile against installed versions of the dependencies please
check the [INSTALL.md file](INSTALL.md).

If you prefer to install dependencies at a custom location and want to compile
against it, please check the instruction at [build with CMake](./doc/setup-cmake-environment.md).

#### macOS

```bash
export OPENSSL_ROOT_DIR=/usr/local/opt/libressl
# Add -DBUILD_TESTING=OFF to disable tests
cmake -Hsuper -Bcmake-out

# Adjust the number of threads used by modifying parameter for `-j 4`
cmake --build cmake-out -- -j 4

# Verify build by running tests
(cd cmake-out && ctest --output-on-failure)
```

You will find compiled binaries in `cmake-out/` respective to their source paths.
You will find compiled binaries in `cmake-out/` respective to their source
paths.

If you prefer to compile against installed versions of the dependencies please
check the [INSTALL.md file](INSTALL.md).

##### Problems with `/usr/include` on macOS Mojave (and later).

If you see the following error:

```bash
CMake Error in google/cloud/storage/CMakeLists.txt:
  Imported target "CURL::libcurl" includes non-existent path

    "/usr/include"
```

you [need to update your Xcode version](https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja).
Install the package located at
`/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

and run:

```bash
xcode-select -s /Library/Developer/CommandLineTools
```

#### Windows

<!-- Last updated 2018-01-09 -->

If you prefer to manually compile on Windows the following instructions should
work, though there is a lot more variability on this platform. We welcome
suggestions to make this an easier process.

We will assume that you have installed CMake, Ninja, and "Microsoft Visual
Studio 2017". If you have not, install [Chocolatey](https://www.chocolatey.org)
using this command as the administrator:

```console
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command ^
 "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
```

Then you can easily install the necessary development tools.

```console
choco install -y cmake cmake.portable ninja visualstudio2017community
choco install -y visualstudio2017-workload-nativedesktop
choco install -y microsoft-build-tools
choco install -y git
```

Then clone and compile `vcpkg`:

```console
set SOURCE="%cd%"
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
```

Use `vcpkg` to download and install `google-cloud-cpp`'s dependencies:

```console
.\vcpkg.exe install openssl:x64-windows-static ^
    grpc:x64-windows-static ^
    gtest:x64-windows-static ^
    googleapis:x64-windows-static
.\vcpkg.exe integrate install
```

Now clone `google-cloud-cpp`:

```console
cd ..
git clone https://github.com/googleapis/google-cloud-cpp.git
cd google-cloud-cpp
```

Load the environment variables needed to use Microsoft Visual Studio:

```console
call "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
```

Use CMake to create the build files:

```console
cmake -H. -Bcmake-out -GNinja ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_TOOLCHAIN_FILE="%SOURCE%\vcpkg\scripts\buildsystems\vcpkg.cmake" ^
    -DVCPKG_TARGET_TRIPLET=x64-windows-static ^
    -DCMAKE_C_COMPILER=cl.exe ^
    -DCMAKE_CXX_COMPILER=cl.exe ^
    -DCMAKE_MAKE_PROGRAM=ninja
```

And compile the code:

```console
cmake --build cmake-out
```

Finally, verify the unit tests pass:

```console
cd cmake-out
ctest --output-on-failure
```

You will find compiled binaries in `cmake-out\` respective to their
source directories.

### Install

By default `google-cloud-cpp` downloads and compiles all its dependencies.
The default configuration disables the `install` target, because the version of
the dependencies downloaded by `google-cloud-cpp` may conflict with the versions
already installed in your system, or with the versions you want to use for
development.

To install `google-cloud-cpp` you must first install all its dependencies. Then
you must configure `google-cloud-cpp` to find these dependencies, and install
it.

Installing the dependencies themselves may be as simple as using the package
manager for your platform, or may require manually downloading, compiling, and
installing said dependencies.  The [INSTALL.md](INSTALL.md) file describes how
to successfully install `google-cloud-cpp` on several platforms.

Alternatively, if you prefer to use `google-cloud-cpp` as a submodule, you can
use the CMake command
[`add_subdirectory()`](https://cmake.org/cmake/help/latest/command/add_subdirectory.html)
to include `google-cloud-cpp` directly in your CMake project.

## Versioning

Please note that the Google Cloud C++ client libraries do **not** follow
[Semantic Versioning](http://semver.org/).

**GA**: Libraries defined at a GA quality level are expected to be stable and
any backwards-incompatible changes will be noted in the documentation. Major
changes to the API will signaled by changing major version number
(e.g. 1.x.y -> 2.0.0).

**Beta**: Libraries defined at a Beta quality level are expected to be mostly
stable and we're working towards their release candidate. We will address issues
and requests with a higher priority.

**Alpha**: Libraries defined at an Alpha quality level are still a
work-in-progress and are more likely to get backwards-incompatible updates.
Additionally, it's possible for Alpha libraries to get deprecated and deleted
before ever being promoted to Beta or GA.

## Contributing changes

See [`CONTRIBUTING.md`](CONTRIBUTING.md) for details on how to contribute to
this project, including how to build and test your changes as well as how to
properly format your code.

## Licensing

Apache 2.0; see [`LICENSE`](LICENSE) for details.
_EOF_
